apiVersion: doris.selectdb.com/v1
kind: DorisCluster
metadata:
  annotations:
    {}
  labels:
    app.kubernetes.io/name: doris
    app.kubernetes.io/instance: doris
    app.kubernetes.io/part-of: doris-operator
  name: doris
  namespace: gaozh
spec:
  feSpec:
    replicas: 3
    image: 172.22.96.158/system_containers/doris-fe:2.0.2
    service:
      type: NodePort
    limits:
      cpu: 8
      memory: 16Gi
    requests:
      cpu: 100m
      memory: 1Gi
    persistentVolumes:
    - mountPath: /opt/apache-doris/fe/doris-meta
      name: fe-meta
      persistentVolumeClaimSpec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: openebs-localpv
  beSpec:
    replicas: 3
    image: 172.22.96.158/system_containers/doris-be:2.0.2
    service:
      type: ClusterIP
    limits:
      cpu: 8
      memory: 16Gi
    requests:
      cpu: 100m
      memory: 1Gi
    persistentVolumes:
    - mountPath: /opt/apache-doris/be/log
      name: be-log
      persistentVolumeClaimSpec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: openebs-localpv
    - mountPath: /opt/apache-doris/be/storage
      name: be-storage
      persistentVolumeClaimSpec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: openebs-localpv
