# Default values for operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  rbac:
    # if set true, the clusterrole, clusterrolebinding, role, rolebinding, serviceaccount resources will be created for
    # operator.
    create: true

nameOverride: "doris"

dorisOperator:
  enabled: true
  # annotations for doris operator.
  annotations: {}
  image:
    repository: 172.22.96.158/system_containers/doris-operator
    tag: 1.3.0
  replicaCount: 1
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
    requests:
      cpu: "100m"
      memory: 256Mi
  # If specified, the pod's nodeSelector，displayName="Map of nodeSelectors to match when scheduling pods on nodes"
  # Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
  nodeSelector: {}
